diploiTemplateVersion: V1.0
name: diploi-ollama-template
description: Diploi Ollama Template
defaultName: Ollama

stages:
  - name: Development
    identifier: development
  - name: Staging
    identifier: staging
  - name: Production
    identifier: production

environmentVariables:
  - identifier: TOPIC
    type: string
    contexts: label=app

contexts:
  - name: app
    identifier: app

repositories:
  - name: app
    identifier: app

hosts:
  - name: App
    identifier: app
    urlFormat: '[label].[default-domain]'

ssh:
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - development
  - usernameFormat: '[label]-[index]'
    contexts: label=app
    stages:
      - production
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - staging
logs:
  - identifier: ollama-server
    name: Ollama Server logs
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/ollama-server.log
  - identifier: ai-talk-ai
    name: AI talks to another AI
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/ai-talk-ai.log

images:
  - identifier: app
    repository: app
    dockerfile: Dockerfile
    image: ghcr.io/filbe/diploi-ollama-template
    initialProjectImage: ghcr.io/filbe/diploi-ollama-template
    stages:
      - development
      - production
      - staging
    manualBuildStages:
      - development

storage:
  - identifier: app
    stages:
      - development
    sizeMiB: 5000

status:
  url: http://app:3000/status

requirements:
  ramGiB: 8